apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubelet-cadvisor
spec:
  path: /metrics/cadvisor
  scheme: https
  port: "10250"
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  tlsConfig:
    insecureSkipVerify: true