---
prometheus-node-exporter:
  fullnameOverride: "node-exporter"

  tolerations:
    - key: "type"
      operator: "Equal"
      value: "cache"
      effect: "NoExecute"
    - key: "type"
      operator: "Equal"
      value: "database"
      effect: "NoExecute"
  priorityClassName: "platform-critical"