apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-infrastructure
  namespace: '{{ .Release.Namespace }}'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/text-adi/k8s-cluster-infrastructure.git'
    ref: dev
    path: 'infrastructure/kustomize'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: '{{ .Release.Namespace }}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
