---
pdbDefaults: &pdbDefaults
  enabled: true
  minAvailable: 50%
  unhealthyPodEvictionPolicy: AlwaysAllow

networkPolicy: &networkPolicyDefaults
  create: true

metrics: &metricsDefaults
  enabled: true
  serviceMonitor:
    enabled: true

argo-cd:
  configs:
    cm:
      timeout.reconciliation: 15s

  controller:
    pdb: *pdbDefaults
    networkPolicy: *networkPolicyDefaults
    dynamicClusterDistribution: true
    replicas: 2
    metrics: *metricsDefaults
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-application-controller
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-application-controller

  dex:
    networkPolicy: *networkPolicyDefaults

  redis:
    networkPolicy: *networkPolicyDefaults
    exporter:
      enabled: true
    metrics: *metricsDefaults

  server:
    pdb: *pdbDefaults
    networkPolicy: *networkPolicyDefaults
    replicas: 2
    metrics: *metricsDefaults
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-server
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-server

  repoServer:
    pdb: *pdbDefaults
    networkPolicy: *networkPolicyDefaults
    replicas: 2
    metrics: *metricsDefaults
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-repo-server
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-repo-server

  applicationSet:
    pdb: *pdbDefaults
    networkPolicy: *networkPolicyDefaults
    replicas: 2
    metrics: *metricsDefaults
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-applicationset-controller
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: argocd-applicationset-controller


  notifications:
    networkPolicy: *networkPolicyDefaults
    metrics: *metricsDefaults

