---
apiVersion: v2
name: kube-state-metrics
description: Wrapper chart to deploy upstream kube-state-metrics via Argo CD
version: 0.1.0
dependencies:
  - name: kube-state-metrics
    version: 8.6.0
    repository: https://prometheus-community.github.io/helm-charts