apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Grafana, Prometheus/VictoriaMetrics стек, kube-state-metrics, metrics-server"
  sourceRepos:
    - 'https://github.com/text-adi/k8s-cluster-infrastructure.git'
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: grafana
    - server: 'https://kubernetes.default.svc'
      namespace: grafana-operator
    - server: 'https://kubernetes.default.svc'
      namespace: monitoring
    - server: 'https://kubernetes.default.svc'
      namespace: kube-system
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'