apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-security
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Vault, Vault Secrets Operator, cert-manager — секрети та сертифікати"
  sourceRepos:
    - 'https://github.com/text-adi/k8s-cluster-infrastructure.git'
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: vault
    - server: 'https://kubernetes.default.svc'
      namespace: vault-secrets-operator
    - server: 'https://kubernetes.default.svc'
      namespace: cert-manager
  clusterResourceWhitelist:
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'cert-manager.io'
      kind: ClusterIssuer
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: "admissionregistration.k8s.io"
      kind: "MutatingWebhookConfiguration"
    - group: "admissionregistration.k8s.io"
      kind: "ValidatingWebhookConfiguration"
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'