apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vertical-pod-autoscaler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-core
  source:
    repoURL: 'https://github.com/text-adi/k8s-cluster-infrastructure.git'
    targetRevision: dev
    path: infrastructure/charts/vertical-pod-autoscaler
    helm:
      releaseName: vertical-pod-autoscaler
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vpa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true