---
victoria-metrics-operator:
  crds:
    enabled: false

  replicaCount: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  resources:
    requests:
      cpu: 80m
      memory: 50Mi

  priorityClassName: "platform-critical"

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: victoria-metrics-operator
          app.kubernetes.io/instance: victoria-metrics-operator
      matchLabelKeys:
        - pod-template-hash

    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: victoria-metrics-operator
          app.kubernetes.io/instance: victoria-metrics-operator
      matchLabelKeys:
        - pod-template-hash