apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - priority-classes.yaml
  - monitoring/metrics-server.yaml
  - monitoring/kube-state-metrics.yaml
  - monitoring/prometheus-node-exporter.yaml
  - vpa.yaml
  - monitoring/victoria-metrics-operator.yaml
  - monitoring/victoria-metrics-operator-crds.yaml
  - monitoring/prometheus-operator-crds.yaml
  - monitoring/victoria-metrics-stack.yaml
  - envoy-gateway-crds.yaml
  - envoy-gateway.yaml
  - grafana.yaml