apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: priority-classes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/text-adi/k8s-cluster-infrastructure.git'
    targetRevision: dev
    path: infrastructure/charts/priority-classes
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true