apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-operator-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/text-adi/k8s-cluster-infrastructure.git'
    targetRevision: dev
    path: infrastructure/charts/victoria-metrics-operator-crds
    helm:
      releaseName: victoria-metrics-operator-crds
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true,
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true