apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vm-agent
spec:
  selectAllByDefault: true
  priorityClassName: "platform-critical"
  statefulMode: true
  remoteWrite:
    - url: "http://vmsingle-victoria-storage.monitoring.svc.cluster.local:8428/api/v1/write"