apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: victoria-storage
  namespace: monitoring
spec:
  retentionPeriod: "30d"
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 20Gi