apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vm-agent
spec:
  selectAllByDefault: true
  serviceAccountName: vm-agent
  priorityClassName: "platform-critical"
  statefulMode: true
