apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-traefik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/text-adi/k8s-cluster-infrastructure.git'
      targetRevision: dev
      path: infrastructure/charts/ingress-controller-traefik
      helm:
        releaseName: ingress-controller-traefik
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
