---
traefik:
  service:
    spec:
      type: NodePort

  ports:
    web:
      nodePort: 30080
    websecure:
      nodePort: 30443

  metrics:
    prometheus:
      service:
        enabled: true
      serviceMonitor:
        enabled: true
        interval: "15s"
        scrapeTimeout: "10s"